services:
  postgres:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_USER: sobhan
      POSTGRES_PASSWORD: 337459azA
      POSTGRES_DB: blog_app_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
