services:
  migrate:
    build: ./backend
    command: npx node-pg-migrate up -m src/infrastructure/db/postgres/migrations
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - migrate

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_USER: sobhan
      POSTGRES_PASSWORD: 337459azA
      POSTGRES_DB: blog_app_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
