export const ERROR_CODES = {
	USER_NOT_FOUND: {
		code: 'USER_NOT_FOUND',
		fa_message: 'کاربر پیدا نشد',
		en_message: 'User not found',
		status: 404,
	},
	VALIDATION_FAILED: {
		code: 'VALIDATION_FAILED',
		fa_message: 'اعتبارسنجی ناموفق بود',
		en_message: 'Validation failed',
		status: 400,
	},
	INTERNAL_SERVER_ERROR: {
		code: 'INTERNAL_SERVER_ERROR',
		fa_message: 'خطای داخلی سرور',
		en_message: 'Internal server error',
		status: 500,
	},
	EMAIL_ALREADY_EXISTS: {
		code: 'EMAIL_ALREADY_EXISTS',
		fa_message: 'این ایمیل قبلاً ثبت شده است',
		en_message: 'Email already exists',
		status: 409,
	},
	USERNAME_ALREADY_EXISTS: {
		code: 'USERNAME_ALREADY_EXISTS',
		fa_message: 'این نام کاربری قبلاً ثبت شده است',
		en_message: 'Username already exists',
		status: 409,
	},
	POST_NOT_FOUND: {
		code: 'POST_NOT_FOUND',
		fa_message: 'پست پیدا نشد',
		en_message: 'Post not found',
		status: 404,
	},
	COMMENT_NOT_FOUND: {
		code: 'COMMENT_NOT_FOUND',
		fa_message: 'کامنت پیدا نشد',
		en_message: 'Comment not found',
		status: 404,
	},
	INVALID_EMAIL_OR_PASS: {
		code: 'INVALID_EMAIL_OR_PASS',
		fa_message: 'رمز یا ایمیل اشتباه وارد شد',
		en_message: 'Wrong email or password entered',
		status: 400,
	},
	UNAUTHORIZED: {
		code: 'PERMISSION_DENIED',
		fa_message: 'شما دسترسی کافی برای این عمل را ندارد',
		en_message: 'You do not have permission',
		status: 403,
	},
	PERMISSION_DENIED: {
		code: 'PERMISSION_DENIED',
		fa_message: 'شما دسترسی کافی برای این عمل را ندارد',
		en_message: 'You do not have permission',
		status: 403,
	},
	NO_PERMISSION_TO_ADD_ADMIN: {
		code: 'NO_PERMISSION_TO_ADD_ADMIN',
		fa_message: 'شما دسترسی کافی برای افزودن ادمین را ندارید',
		en_message: 'You do not have permission to add admin',
		status: 403,
	},
	NO_PERMISSION_TO_ADD_SUPER_ADMIN: {
		code: 'NO_PERMISSION_TO_ADD_SUPER_ADMIN',
		fa_message: 'شما دسترسی کافی برای افزودن سوپر ادمین را ندارید',
		en_message: 'You do not have permission to add super admin',
		status: 403,
	},
	NO_PERMISSION_TO_UPDATE_ADMIN: {
		code: 'NO_PERMISSION_TO_UPDATE_ADMIN',
		fa_message: 'شما دسترسی کافی برای آپدیت ادمین را ندارید',
		en_message: 'You do not have permission to update admin',
		status: 403,
	},
	NO_PERMISSION_TO_UPDATE_OTHER_SUPERADMIN: {
		code: 'NO_PERMISSION_TO_UPDATE_OTHER_SUPERADMIN',
		fa_message: 'شما دسترسی کافی برای آپدیت سایر سوپر ادمین‌ها را ندارید',
		en_message: 'You do not have permission to update other super admin',
		status: 403,
	},
	NO_PERMISSION_TO_UPDATE_FIELD: {
		code: 'NO_PERMISSION_TO_UPDATE_FIELD',
		fa_message: 'حق آپدیت این فیلد را ندارید',
		en_message: 'You do not have permission to update this feild.',
		status: 403,
	},
};
